### ISSUE TITLE
CSV not compatible with newest Modbus Adapter 5.0.5

### ISSUE THREAD

**Issue by MrDrache333** [mccrossen/iobroker-modbus-e3dc#1]
THe new Modbus ADapter requires not TSV but CSV Table format with the following colums
`_address	deviceId	name	description	unit	type	len	factor	offset	formula	role	room	poll	wp	cw	isScale
`
Ive updated it and created a pullrequest #2

**Comment by mccrossen** [comment]
Thank you for update to tsv table format.
